package com.example.module12methodbasedsecurity.security;

public interface UserRoles {

    String PREFIX = "ROLE_";

    String SUPER_ADMIN = "SUPER_ADMIN";
    String EMPLOYEE_ADMIN = "EMPLOYEE_ADMIN";
    String CUSTOMER_ADMIN = "CUSTOMER_ADMIN";
    String DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN";

    String EMPLOYEE_READ = "EMPLOYEE_READ";
    String EMPLOYEE_CREATE = "EMPLOYEE_CREATE";
    String EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE";
    String EMPLOYEE_DELETE = "EMPLOYEE_DELETE";

    String CUSTOMER_READ = "CUSTOMER_READ";
    String CUSTOMER_CREATE = "CUSTOMER_CREATE";
    String CUSTOMER_UPDATE = "CUSTOMER_UPDATE";
    String CUSTOMER_DELETE = "CUSTOMER_DELETE";

    String DEPARTMENT_READ = "DEPARTMENT_READ";
    String DEPARTMENT_CREATE = "DEPARTMENT_CREATE";
    String DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE";
    String DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
}
