spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: COUNTER-SERVICE
          uri: lb://COUNTER-SERVICE
          predicates:
            - Path=/counter/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
